name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  
jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Check out code
        uses: actions/checkout@v1

      - name: Run Unit tests.
        run: go test
      
      

  build:
    name: Build
    runs-on: ubuntu-latest 
    needs: [ test]
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Check out code
        uses: actions/checkout@v1

      - name: Build
        run: make build
